Znaika\FrontendBundle\Entity\Communication\Message:
    type: entity
    table: message
    repositoryClass: Znaika\FrontendBundle\Repository\Communication\MessageDBRepository
    fields:
        messageId:
            column: message_id
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        thread:
            targetEntity: Znaika\FrontendBundle\Entity\Communication\Thread
            inversedBy: messages
            joinColumn:
                name: thread_id
                referencedColumnName: thread_id
                onDelete: CASCADE
        sender:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            joinColumn:
                name: sender_id
                referencedColumnName: user_id
                onDelete: CASCADE
    oneToMany:
        metadata:
            targetEntity: Znaika\FrontendBundle\Entity\Communication\MessageMetadata
            mappedBy:     message
            cascade:      [all]
    lifecycleCallbacks: {  }
