Znaika\FrontendBundle\Entity\Communication\MessageMetadata:
    type: entity
    table: message_metadata
    fields:
        messageMetadataId:
            column: message_metadata_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        isDeleted:
            column: is_deleted
            type: boolean
    manyToOne:
        message:
            targetEntity: Znaika\FrontendBundle\Entity\Communication\Message
            inversedBy: metadata
            joinColumn:
                name: message_id
                referencedColumnName: message_id
                onDelete: CASCADE
        participant:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            joinColumn:
                name: participant_id
                referencedColumnName: user_id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
