Znaika\FrontendBundle\Entity\Education\School:
    type: entity
    table: school
    fields:
        schoolId:
            column: school_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    oneToMany:
        classrooms:
            targetEntity: Znaika\FrontendBundle\Entity\Education\Classroom
            mappedBy: school
        users:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            mappedBy: school
    manyToOne:
        city:
            targetEntity: Znaika\FrontendBundle\Entity\Location\City
            inversedBy: schools
            joinColumn:
                name: city_id
                referencedColumnName: city_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }