Znaika\FrontendBundle\Entity\Education\Classroom:
    type: entity
    table: classroom
    fields:
        classroomId: { column: classroom_id, type: integer, id: true, generator: { strategy: AUTO } }
        grade:       { type: integer }
        letter:      { type: string, length: 255 }
    oneToMany:
        users:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            mappedBy: classrooms
    manyToOne:
        school:
            targetEntity: Znaika\FrontendBundle\Entity\Education\School
            inversedBy: classrooms
            joinColumn:
                name: school_id
                referencedColumnName: school_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }