Znaika\FrontendBundle\Entity\Lesson\Content\VideoComment:
    type: entity
    table: video_comment
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\VideoCommentDBRepository
    fields:
        videoCommentId:
            column: video_comment_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
            notnull: true
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        video:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            inversedBy: videoComments
            joinColumn:
                name: video_id
                referencedColumnName: video_id
                onDelete: CASCADE
        userInfo:
            targetEntity: Znaika\FrontendBundle\Entity\User\UserInfo
            inversedBy: videoComments
            joinColumn:
                name: user_info_id
                referencedColumnName: user_info_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }
