Znaika\FrontendBundle\Entity\Lesson\Content\VideoView:
    type: entity
    table: video_view
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\VideoViewDBRepository
    fields:
        videoViewId:
            column: video_view_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        video:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            inversedBy: videoViews
            joinColumn:
                name: video_id
                referencedColumnName: video_id
                onDelete: CASCADE
        user:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: videoViews
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }
