Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\QuizQuestion:
    type: entity
    table: quiz_question
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\QuizQuestionDBRepository
    fields:
        quizQuestionId: { column: quiz_question_id, type: integer, id: true, generator: { strategy: AUTO } }
        text:           { type: text, notnull: true }
        type:           { type: smallint, notnull: true }
        createdTime:    { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    manyToOne:
        video:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            inversedBy: quizQuestions
            joinColumn:
                name: video_id
                referencedColumnName: video_id
                onDelete: CASCADE
    oneToMany:
        quizAnswers:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\QuizAnswer
            mappedBy:     quizQuestion
            cascade:      [persist]
    lifecycleCallbacks: {  }
