Znaika\FrontendBundle\Entity\Lesson\Content\Video:
    type: entity
    table: video
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\VideoDBRepository
    fields:
        videoId:            { column: video_id, type: integer, id: true, generator: { strategy: AUTO } }
        name:               { type: string, length: 255, notnull: true }
        grade:              { type: integer, notnull: true }
        urlName:            { column: url_name, type: string, length: 128, notnull: true, unique: true }
        url:                { column: url, type: string, length: 255, notnull: true }
        smallThumbnailUrl:  { column: small_thumbnail_url, type: string, length: 255, nullable: true }
        mediumThumbnailUrl: { column: medium_thumbnail_url, type: string, length: 255, nullable: true }
        largeThumbnailUrl:  { column: large_thumbnail_url, type: string, length: 255, nullable: true }
        views:              { type: integer, notnull: true }
        author:             { type: string, length: 255, notnull: true }
        orderPriority:      { column: order_priority, type: integer, notnull: true }
        createdTime:        { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    oneToOne:
        synopsis:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Synopsis
            inversedBy: video
            joinColumn:
                name: synopsis_id
                referencedColumnName: synopsis_id
                onDelete: "SET NULL"
        quiz:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\Quiz
            inversedBy: video
            joinColumn:
                name: quiz_id
                referencedColumnName: quiz_id
                onDelete: "SET NULL"
    manyToOne:
        chapter:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Category\Chapter
            inversedBy: videos
            joinColumn:
                name: chapter_id
                referencedColumnName: chapter_id
                onDelete: CASCADE
        subject:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Category\Subject
            inversedBy: videos
            joinColumn:
                name: subject_id
                referencedColumnName: subject_id
                onDelete: CASCADE
    oneToMany:
        videoComments:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\VideoComment
            mappedBy:     video
            cascade:      [persist]
        videoAttachments:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\VideoAttachment
            mappedBy:     video
            cascade:      [persist]
    manyToMany:
        supervisors:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: supervisedVideos
            joinTable:
                name: video_supervisor
                joinColumns:
                    video_id:
                        referencedColumnName: video_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id
                        onDelete: CASCADE
    lifecycleCallbacks: {  }
