Znaika\FrontendBundle\Entity\Lesson\Content\Video:
    type: entity
    table: video
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\VideoDBRepository
    fields:
        videoId:
            column: video_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            notnull: true
        grade:
            type: integer
            notnull: true
        urlName:
            column: url_name
            type: string
            length: 128
            notnull: true
            unique: true
        url:
            column: url
            type: string
            length: 255
            notnull: true
        views:
            type: integer
            notnull: true
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    oneToOne:
        synopsis:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Synopsis
            inversedBy: video
            joinColumn:
                name: synopsis_id
                referencedColumnName: synopsis_id
    manyToOne:
        chapter:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Category\Chapter
            inversedBy: videos
            joinColumn:
                name: chapter_id
                referencedColumnName: chapter_id
                onDelete: CASCADE
        subject:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Category\Subject
            inversedBy: videos
            joinColumn:
                name: subject_id
                referencedColumnName: subject_id
                onDelete: CASCADE
    oneToMany:
        videoComments:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\VideoComment
            mappedBy:     video
            cascade:      [persist]
        quizQuestions:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\QuizQuestion
            mappedBy:     video
            cascade:      [persist]
        userAttempts:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\Attempt\UserAttempt
            mappedBy:     video
            cascade:      [persist]
        videoAttachments:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\VideoAttachment
            mappedBy:     video
            cascade:      [persist]
    manyToMany:
        similarVideos:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            inversedBy: similarToVideos
            joinTable:
                name: similar_videos
                joinColumns:
                    video_id:
                        referencedColumnName: video_id
                inverseJoinColumns:
                    similar_video_id:
                        referencedColumnName: video_id
        similarToVideos:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            mappedBy: similarVideos
    lifecycleCallbacks: {  }
