Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\Attempt\UserAttempt:
    type: entity
    table: user_attempt
    repositoryClass: Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\Attempt\UserAttemptDBRepository
    fields:
        userAttemptId:
            column: user_attempt_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        video:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Video
            inversedBy: userAttempts
            joinColumn:
                name: video_id
                referencedColumnName: video_id
                onDelete: CASCADE
        user:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: userAttempts
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: CASCADE
    oneToMany:
        userQuestionAnswers:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\Quiz\Attempt\UserQuestionAnswer
            mappedBy:     userAttempt
            cascade:      [persist]
    lifecycleCallbacks: {  }
