Znaika\FrontendBundle\Entity\Lesson\Content\Video:
    type: entity
    table: video
    repositoryClass: Znaika\FrontendBundle\Entity\Lesson\Content\VideoDBRepository
    fields:
        videoId:
            column: video_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            notnull: true
        grade:
            type: integer
            notnull: true
        urlName:
            column: url_name
            type: string
            length: 128
            notnull: true
        url:
            column: url
            type: string
            length: 255
            notnull: true
        createdTime:
            column: created_time
            type: datetime
            notnull: true
    manyToOne:
        subject:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Category\Subject
            inversedBy: videos
            joinColumn:
                name: subject_id
                referencedColumnName: subject_id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
