Znaika\FrontendBundle\Entity\Location\City:
    type: entity
    table: city
    fields:
        cityId:
            column: city_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    oneToMany:
        users:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            mappedBy: city
        schools:
            targetEntity: Znaika\FrontendBundle\Entity\Education\School
            mappedBy: city
    lifecycleCallbacks: {  }
