Znaika\FrontendBundle\Entity\Profile\Action\JoinSocialNetworkCommunityOperation:
    type: entity
    fields:
        socialNetwork:
            column: social_network
            type: smallint
            nullable: true