Znaika\FrontendBundle\Entity\Profile\Badge\BaseUserBadge:
    type: entity
    table: user_badge
    repositoryClass: Znaika\FrontendBundle\Repository\Profile\Badge\UserBadgeDBRepository
    fields:
        userBadgeId:
            column: user_badge_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        user:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: userBadges
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: "SET NULL"
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        fieldName: badgeType
        name: badge_type
        type: smallint
    discriminatorMap:
        0: Znaika\FrontendBundle\Entity\Profile\Badge\BaseUserBadge
        1: Znaika\FrontendBundle\Entity\Profile\Badge\FilledOutProfileBadge
        2: Znaika\FrontendBundle\Entity\Profile\Badge\ViewVideosBadge

    lifecycleCallbacks: {  }