Znaika\FrontendBundle\Entity\Profile\ChangeUserEmail:
    type: entity
    table: change_user_email
    repositoryClass: Znaika\FrontendBundle\Repository\Profile\ChangeUserEmailDBRepository
    fields:
        changeUserEmailId: { column: change_user_email_id, type: integer, id: true, generator: { strategy: AUTO } }
        changeKey:         { column: change_key, type: string, length: 255, notnull: true, unique: true }
        newEmail:          { column: newEmail, type: string, length: 255, notnull: true }
        createdTime:       { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    manyToOne:
        user:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: userRegistrations
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }
