Znaika\FrontendBundle\Entity\Profile\PasswordRecovery:
    type: entity
    table: password_recovery
    repositoryClass: Znaika\FrontendBundle\Repository\Profile\PasswordRecoveryDBRepository
    fields:
        passwordRecoveryId:
            column: password_recovery_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        recoveryKey:
            column: recovery_key
            type: string
            length: 255
            notnull: true
            unique: true
        recoveryTime:
            column: recovery_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        user:
            targetEntity: Znaika\FrontendBundle\Entity\Profile\User
            inversedBy: passwordRecoveries
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }
