Znaika\FrontendBundle\Entity\User\UserInfo:
    type: entity
    table: user_info
    repositoryClass: Znaika\FrontendBundle\Repository\User\UserInfoDBRepository
    fields:
        userInfoId:
            column: user_info_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        firstName:
            column: first_name
            type: string
            length: 255
        lastName:
            column: last_name
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
            notnull: true
        password:
            type: string
            length: 255
            notnull: true
        createdTime:
            column: created_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
