Znaika\ProfileBundle\Entity\PasswordRecovery:
    type: entity
    table: password_recovery
    repositoryClass: Znaika\ProfileBundle\Repository\PasswordRecoveryDBRepository
    fields:
        passwordRecoveryId:
            column: password_recovery_id
            type: integer
            id: true
            generator:
                strategy: AUTO
        recoveryKey:
            column: recovery_key
            type: string
            length: 255
            notnull: true
            unique: true
        recoveryTime:
            column: recovery_time
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        user:
            targetEntity: Znaika\ProfileBundle\Entity\User
            inversedBy: passwordRecoveries
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: "SET NULL"
    lifecycleCallbacks: {  }
