Znaika\ProfileBundle\Entity\Region:
    type: entity
    table: region
    repositoryClass: Znaika\ProfileBundle\Repository\RegionDBRepository
    fields:
        regionId: { column: region_id, type: integer, id: true, generator: { strategy: AUTO } }
        regionName: { column: region_name, type: string, length: 255, notnull: true, unique: true }
        createdTime: { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    oneToMany:
        users:
            targetEntity: Znaika\ProfileBundle\Entity\User
            mappedBy: region
    lifecycleCallbacks: {  }
