Znaika\ProfileBundle\Entity\UserParentRelation:
    type: entity
    table: user_parent_relation
    repositoryClass: Znaika\ProfileBundle\Repository\UserParentRelationDBRepository
    fields:
        userParentRelationId: { column: user_parent_relation_id, type: integer, id: true, generator: { strategy: AUTO } }
        approved:             { column: approved, type: boolean }
        createdTime:          { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    manyToOne:
        child:
            targetEntity: Znaika\ProfileBundle\Entity\User
            inversedBy: childRelations
            joinColumn:
                name: child_id
                referencedColumnName: user_id
                onDelete: CASCADE
        parent:
            targetEntity: Znaika\ProfileBundle\Entity\User
            inversedBy: parentRelations
            joinColumn:
                name: parent_id
                referencedColumnName: user_id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
