<?php

namespace Znaika\FrontendBundle\Entity\Lesson\Content;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function getVideosForCatalog($classNumber = null, $subjectName = null)
    {
        $videos = $this->getEntityManager()
                       ->createQueryBuilder()
                       ->select('v')
                       ->from('ZnaikaFrontendBundle:Lesson\Content\Video', 'v')
                       ->innerJoin('v.subject','s')
                       ->where('s.urlName = :subjectName')
                       ->orWhere('v.grade = :classNumber')
                       ->addOrderBy('v.createdTime', 'DESC')
                       //->setMaxResults(3) TODO: set limit
                       ->setParameter('subjectName', $subjectName)
                       ->setParameter('classNumber', $classNumber)
                       ->getQuery()
                       ->getResult();

        return $videos;
    }
}
