imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
#
#monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
#        nested:
#            type:  stream
#            path:  %kernel.logs_dir%/%kernel.environment%.log
#            level: debug


parameters:
    vimeo_client_id:           f17911c69b8310bf7639f9580feb4f0ffa4ec696
    vimeo_client_secret:       96b25f825a1999dbc0348e6559d958d5fd97521b
    vimeo_access_token:        3df2402843f89d75b015892c82734087
    vimeo_access_token_secret: d10d31c5c2f09053679b3e281b4424dc90445414

    upload_file_dir: /var/www/znaika/web/uploads/

    vk_client_id:     4189574
    vk_client_secret: VKKmEUUmZuLf9xb9EVTB
    vk_redirect_uri:  http://znaika.local/vk-auth

    facebook_client_id:     738615669489662
    facebook_client_secret: b1a4797dc63a8bd6c92c6305f258a9ec
    facebook_redirect_uri:  http://znaika.local/facebook-auth

    odnoklassniki_client_id:     223869184
    odnoklassniki_public_key:    CBAKPIFOABABABABA
    odnoklassniki_client_secret: E36998B37C434A20950F618E
    odnoklassniki_redirect_uri:  http://znaika.local/odnoklassniki-auth

    support_emails: ["ilya.shikhaleev@cpslabs.net"]
    error_report_emails: ["ilya.shikhaleev@cpslabs.net"]