imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ZnaikaProfileBundle/Resources/config/services.yml }
    - { resource: @ZnaikaFrontendBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'ZnaikaFrontendBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['ZnaikaFrontendBundle', 'TwigBundle', 'ZnaikaProfileBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            string_functions:
                field: Znaika\FrontendBundle\DQL\MysqlField

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

monolog:
    handlers:
        main:
            level:    error
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_remaining.log"
            channels: ["!doctrine", "!request", "!security"]
        request:
            type:    fingers_crossed
            handler: requests
            excluded_404s:
                - ^/phpmyadmin
        requests:
            type:    group
            members: [request_critical, request_error]
        request_critical:
            level:    critical
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_request_critical.log"
            channels: [request]
        request_error:
            level:    error
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_request.log"
            channels: [request]
        doctrine:
            level:    error
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_doctrine.log"
            channels: [doctrine]
        security:
            level:    error
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%_security.log"
            channels: [security]
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: error@znaika.ru
            to_email:   %error_report_emails%
            subject:    %error_report_subject%
            level:      debug
            formatter:  email_formatter

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

fos_message:
    db_driver:        orm
    thread_class:     Znaika\FrontendBundle\Entity\Communication\Thread
    message_class:    Znaika\FrontendBundle\Entity\Communication\Message
    message_manager:  znaika.message_repository
    thread_manager:   znaika.thread_repository
    user_transformer: znaika.user_to_id_transformer
    provider:         znaika.messages_provider
    new_thread_form:
        type:         znaika.new_thread_form.type

parameters:
    vimeo_client_id:           f17911c69b8310bf7639f9580feb4f0ffa4ec696
    vimeo_client_secret:       96b25f825a1999dbc0348e6559d958d5fd97521b
    vimeo_access_token:        3df2402843f89d75b015892c82734087
    vimeo_access_token_secret: d10d31c5c2f09053679b3e281b4424dc90445414

    upload_file_dir: /var/www/znaika/web/uploads/

    vk_client_id:     4189574
    vk_client_secret: VKKmEUUmZuLf9xb9EVTB
    vk_redirect_uri:  http://znaika.local/vk-auth

    facebook_client_id:     738615669489662
    facebook_client_secret: b1a4797dc63a8bd6c92c6305f258a9ec
    facebook_redirect_uri:  http://znaika.local/facebook-auth

    odnoklassniki_client_id:     223869184
    odnoklassniki_public_key:    CBAKPIFOABABABABA
    odnoklassniki_client_secret: E36998B37C434A20950F618E
    odnoklassniki_redirect_uri:  http://znaika.local/odnoklassniki-auth

    support_emails: ["ilya.shikhaleev@cpslabs.net", "qwe123qweqwe123@gmail.com"]

    error_report_emails: ["ilya.shikhaleev@cpslabs.net", "qwe123qweqwe123@gmail.com"]
    error_report_subject: Znaika.ru %kernel.environment% Error