security:
    encoders:
        Znaika\FrontendBundle\Entity\User\UserInfo:
            algorithm: sha1
            iterations: 9
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Znaika\FrontendBundle\Entity\User\UserInfo, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _logout
#                target: _demo
            anonymous: ~
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: ^/video, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
