security:
    encoders:
        Znaika\ProfileBundle\Entity\User:
            algorithm: sha1
            iterations: 9
            encode_as_base64: true

    role_hierarchy:
        ROLE_TEACHER:   ROLE_USER
        ROLE_MODERATOR: ROLE_TEACHER
        ROLE_ADMIN:     [ROLE_MODERATOR]

    providers:
        main:
            entity: { class: Znaika\ProfileBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/login$
#            security: false

        secured_area:
            remember_me:
                key:      "%secret%"
                lifetime: 172800 # 48 hours in seconds
                path:     /
                domain:   ~
            pattern:    ^/
            form_login:
                login_path:      login
                check_path:      login_check
                success_handler: znaika.security.authentication_handler
                failure_handler: znaika.security.authentication_handler
            logout:
                path:   /logout
                target: /

            anonymous: ~
            http_basic:
                realm: "Необходима логинация"

    access_control:
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/teacher, roles: ROLE_TEACHER }
        - { path: ^/moderator, roles: ROLE_MODERATOR }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
