security:
    encoders:
        Znaika\FrontendBundle\Entity\Profile\User:
            algorithm: sha1
            iterations: 9
            encode_as_base64: true

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN:     [ROLE_MODERATOR]

    providers:
        main:
            entity: { class: Znaika\FrontendBundle\Entity\Profile\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/login$
#            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout
                target: /

            anonymous: ~
            http_basic:
                realm: "Необходима логинация"

    access_control:
        - { path: ^/login, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
