Znaika\LikesBundle\Entity\VideoCommentLike:
    type: entity
    table: video_comment_like
    repositoryClass: Znaika\LikesBundle\Repository\VideoCommentLikeDBRepository
    fields:
        videoCommentLikeId: { column: video_comment_like_id, type: integer, id: true, generator: { strategy: AUTO } }
        createdTime:        { column: created_time, type: datetime, columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP }
    manyToOne:
        videoComment:
            targetEntity: Znaika\FrontendBundle\Entity\Lesson\Content\VideoComment
            inversedBy: likes
            joinColumn:
                name: video_comment_id
                referencedColumnName: video_comment_id
                onDelete: CASCADE
        user:
            targetEntity: Znaika\ProfileBundle\Entity\User
            inversedBy: videoCommentLikes
            joinColumn:
                name: user_id
                referencedColumnName: user_id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
