znaika_frontend_homepage:
    pattern:  /
    defaults: { _controller: ZnaikaFrontendBundle:Default:index }

show_catalogue:
    pattern: /catalog/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue }
    requirements:
        class:  \d+

show_catalogue_by_class:
    pattern: /catalog/{class}-klass
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, subjectName: null }
    requirements:
        class:  \d+

show_catalogue_by_subject:
    pattern: /catalog/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, class: null }


get_videos:
    pattern: /get-videos
    defaults: { _controller: ZnaikaFrontendBundle:Video:getVideos }
    methods:  [POST]

show_video:
    pattern: /video/{class}-klass/{subjectName}/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showVideo }
    requirements:
        class:  \d+

add_video_form:
    pattern: /video/add-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoForm }

add_synopsis_form:
    pattern: /video/{videoName}/add-synopsis-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addSynopsisForm }