znaika_frontend_homepage:
    pattern:  /
    defaults: { _controller: ZnaikaFrontendBundle:Default:index }

show_catalogue:
    pattern: /catalog/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, subjectName: "" }

show_video:
    pattern: /video/{class}-klass/{subject}/{id}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showVideo }
