znaika_frontend_homepage:
    pattern:  /
    defaults: { _controller: ZnaikaFrontendBundle:Default:index }

show_catalogue:
    pattern: /catalog/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue }
    requirements:
        class:  \d+
    options:
        expose: true

show_catalogue_by_class:
    pattern: /catalog/{class}-klass
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, subjectName: null }
    requirements:
        class:  \d+

show_catalogue_by_subject:
    pattern: /catalog/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, class: null }

get_videos:
    pattern: /get-videos
    defaults: { _controller: ZnaikaFrontendBundle:Video:getVideos }
    methods:  [POST]

show_video:
    pattern: /video/{class}-klass/{subjectName}/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showVideo }
    requirements:
        class:  \d+

add_video_form:
    pattern: /video/add-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoForm }

add_video_comment_form:
    pattern: /{videoName}/add_video_comment_form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoCommentForm }

add_synopsis_form:
    pattern: /video/{videoName}/add-synopsis-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addSynopsisForm }

add_quiz_form:
    pattern: /video/{videoName}/add-quiz-form
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:addQuizForm }

show_quiz:
    pattern: /video/{videoName}/quiz
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:showQuiz }

add_quiz_attempt:
    pattern: /video/quiz_attempt
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:addQuizAttempt }

register:
    pattern: /register
    defaults: { _controller: ZnaikaFrontendBundle:User:register }

show_user_profile:
    pattern: /user/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:showUserProfile }

edit_user_profile:
    pattern: /edit-user-profile/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:editUserProfile }

login:
    path: /user-login
    defaults: { _controller: ZnaikaFrontendBundle:User:login }

login_check:
    path: /login-check

try_login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: add_video_form
        permanent: true

logout:
    path: /logout

search:
    pattern: /search
    defaults: { _controller: ZnaikaFrontendBundle:Search:search }

get_class_subjects:
    pattern: /class/subjects
    defaults: { _controller: ZnaikaFrontendBundle:Default:getClassSubjects }
    methods:  [POST]
    options:
        expose: true