znaika_frontend_homepage:
    pattern:  /
    defaults: { _controller: ZnaikaFrontendBundle:Default:index }

show_catalogue:
    pattern: /catalog/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue }
    requirements:
        class:  \d+
    options:
        expose: true

show_catalogue_by_class:
    pattern: /catalog/{class}-klass
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, subjectName: null }
    requirements:
        class:  \d+

show_catalogue_by_subject:
    pattern: /catalog/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, class: null }

edit_chapters:
    pattern: /edit-chapters/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Chapter:editChapters }
    methods:  [POST]

get_videos:
    pattern: /get-videos
    defaults: { _controller: ZnaikaFrontendBundle:Video:getVideos }
    methods:  [POST]

show_video:
    pattern: /video/{class}-klass/{subjectName}/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showVideo }
    requirements:
        class:  \d+

add_video_form:
    pattern: /moderator/video/{class}-klass/{subjectName}/{chapterName}/add-video-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoForm }

edit_video_form:
    pattern: /moderator/video/{videoName}/edit-video-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:editVideoForm }

add_quiz_form:
    pattern: /moderator/video/{videoName}/quiz-form
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:addQuizForm }

save_quiz_stat_form:
    pattern: /save-quiz-stat
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:saveQuizStat }

add_video_comment_form:
    pattern: /{videoName}/add_video_comment_form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoCommentForm }

question_answer_form:
    pattern: /{videoName}/question_answer_form
    defaults: { _controller: ZnaikaFrontendBundle:Video:questionAnswerForm }

get_prev_comments:
    pattern: /{videoName}/prev-comments
    defaults: { _controller: ZnaikaFrontendBundle:Video:getPrevComments }
    methods:  [POST]

get_video_last_comments:
    pattern: /{videoName}/get-last-comments
    defaults: { _controller: ZnaikaFrontendBundle:Video:getVideoLastComments }
    methods:  [POST]

move_video:
    pattern: /moderator/move-video-ajax
    defaults: { _controller: ZnaikaFrontendBundle:Video:moveVideoAjax }
    methods:  [POST]
    options:
        expose: true

add_synopsis_form:
    pattern: /moderator/video/{videoName}/add-synopsis-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addSynopsisForm }

get_video_not_verified_comments_ajax:
    pattern: /moderator/get-not-verified-comments/{videoId}
    defaults: { _controller: ZnaikaFrontendBundle:Video:getNotVerifiedCommentsAjax }
    methods:  [POST]
    options:
        expose: true

show_threads:
    pattern: /messages
    defaults: { _controller: ZnaikaFrontendBundle:Message:showThreads }

send_message:
    pattern: /send-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:sendMessage }
    methods:  [POST]

show_thread:
    pattern: /dialog/{threadId}
    defaults: { _controller: ZnaikaFrontendBundle:Message:showThread }

new_message:
    pattern: /new-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:newMessage }
    methods:  [POST]

delete_message:
    pattern: /delete-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:deleteMessage }
    methods:  [POST]
    options:
        expose: true



search:
    pattern: /search
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideo }

search_video:
    pattern: /search/video/{searchString}
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideo }

search_video_ajax:
    pattern: /search/next-videos
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideoAjax }
    methods:  [POST]
    options:
        expose: true

add_video_attachment_form:
    pattern: /video/{videoName}/add-video-attachment-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoAttachmentForm }

download_video_attachment:
    pattern: /video-attachment/{attachmentId}
    defaults: { _controller: ZnaikaFrontendBundle:Video:downloadVideoAttachment }
    requirements:
        attachmentId:  \d+

post_video_to_social_network:
    pattern: /post-video/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:postVideoToSocialNetwork }
    methods:  [POST]
    options:
        expose: true

about:
    pattern: /about
    defaults: { _controller: ZnaikaFrontendBundle:Default:about }

contacts:
    pattern: /contacts
    defaults: { _controller: ZnaikaFrontendBundle:Default:contacts }

rules:
    pattern: /rules
    defaults: { _controller: ZnaikaFrontendBundle:Default:rules }

agreement:
    pattern: /agreement
    defaults: { _controller: ZnaikaFrontendBundle:Default:agreement }

support:
    pattern: /support
    defaults: { _controller: ZnaikaFrontendBundle:Support:addSupportForm }

support_create_success:
    pattern: /support-created
    defaults: { _controller: ZnaikaFrontendBundle:Support:supportCreateSuccess }
