znaika_frontend_homepage:
    pattern:  /
    defaults: { _controller: ZnaikaFrontendBundle:Default:index }

show_catalogue:
    pattern: /catalog/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue }
    requirements:
        class:  \d+
    options:
        expose: true

show_catalogue_by_class:
    pattern: /catalog/{class}-klass
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, subjectName: null }
    requirements:
        class:  \d+

show_catalogue_by_subject:
    pattern: /catalog/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showCatalogue, class: null }

edit_chapters:
    pattern: /edit-chapters/{class}-klass/{subjectName}
    defaults: { _controller: ZnaikaFrontendBundle:Chapter:editChapters }
    methods:  [POST]

get_videos:
    pattern: /get-videos
    defaults: { _controller: ZnaikaFrontendBundle:Video:getVideos }
    methods:  [POST]

show_video:
    pattern: /video/{class}-klass/{subjectName}/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:showVideo }
    requirements:
        class:  \d+

add_video_form:
    pattern: /moderator/video/{class}-klass/{subjectName}/{chapterName}/add-video-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoForm }

edit_video_form:
    pattern: /moderator/video/{videoName}/edit-video-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:editVideoForm }

add_quiz_form:
    pattern: /moderator/video/{videoName}/quiz-form
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:addQuizForm }

save_quiz_stat_form:
    pattern: /save-quiz-stat
    defaults: { _controller: ZnaikaFrontendBundle:Quiz:saveQuizStat }

add_video_comment_form:
    pattern: /{videoName}/add_video_comment_form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoCommentForm }

get_prev_comments:
    pattern: /{videoName}/prev-comments
    defaults: { _controller: ZnaikaFrontendBundle:Video:getPrevComments }

move_video:
    pattern: /moderator/move-video-ajax
    defaults: { _controller: ZnaikaFrontendBundle:Video:moveVideoAjax }
    methods:  [POST]
    options:
        expose: true

add_synopsis_form:
    pattern: /moderator/video/{videoName}/add-synopsis-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addSynopsisForm }

register:
    pattern: /register
    defaults: { _controller: ZnaikaFrontendBundle:User:register }
    options:
        expose: true

password_recovery:
    pattern: /forget-password
    defaults: { _controller: ZnaikaFrontendBundle:User:passwordRecovery }

generate_password:
    pattern: /generate-new-password/{recoveryKey}
    defaults: { _controller: ZnaikaFrontendBundle:User:generateNewPassword }

show_user_profile:
    pattern: /user/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:showUserProfile }

edit_user_profile:
    pattern: /edit-user-profile/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:editUserProfile }

edit_teacher_profile:
    pattern: /teacher/edit-profile/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:editTeacherProfile }

teacher_questions:
    pattern: /teacher/questions/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:teacherQuestions }

not_verified_comments:
    pattern: /moderator/not_verified_comments/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:notVerifiedComments }

approve_comments:
    pattern: /moderator/approve-comments
    defaults: { _controller: ZnaikaFrontendBundle:User:approveComments }
    methods:  [POST]
    options:
        expose: true

delete_comments:
    pattern: /moderator/delete-comments
    defaults: { _controller: ZnaikaFrontendBundle:User:deleteComments }
    methods:  [POST]
    options:
        expose: true

not_verified_pupils:
    pattern: /moderator/not_verified_pupils/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:notVerifiedPupils, userId: null }

approve_users:
    pattern: /moderator/approve-users
    defaults: { _controller: ZnaikaFrontendBundle:User:approveUsers }
    methods:  [POST]
    options:
        expose: true

delete_users:
    pattern: /moderator/delete-users
    defaults: { _controller: ZnaikaFrontendBundle:User:deleteUsers }
    methods:  [POST]
    options:
        expose: true

get_user_profile_ajax:
    pattern: /moderator/get-user-profile/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:getUserProfileAjax }
    methods:  [POST]
    options:
        expose: true

get_video_not_verified_comments_ajax:
    pattern: /moderator/get-not-verified-comments/{videoId}
    defaults: { _controller: ZnaikaFrontendBundle:Video:getNotVerifiedCommentsAjax }
    methods:  [POST]
    options:
        expose: true

edit_user_photo:
    pattern: /edit-user-photo/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:editUserPhoto }

delete_user_photo:
    pattern: /delete-user-photo/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:deleteUserPhoto }
    methods:  [POST]
    options:
        expose: true

change_password:
    pattern: /change-password/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:changePassword }
    methods:  [POST]

change_email:
    pattern: /change-email/{userId}
    defaults: { _controller: ZnaikaFrontendBundle:User:changeEmail }
    methods:  [POST]

complete_change_email:
    pattern: /complete-change-email/{key}
    defaults: { _controller: ZnaikaFrontendBundle:User:completeChangeEmail }

show_threads:
    pattern: /messages
    defaults: { _controller: ZnaikaFrontendBundle:Message:showThreads }

send_message:
    pattern: /send-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:sendMessage }
    methods:  [POST]

show_thread:
    pattern: /dialog/{threadId}
    defaults: { _controller: ZnaikaFrontendBundle:Message:showThread }

new_message:
    pattern: /new-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:newMessage }
    methods:  [POST]

delete_message:
    pattern: /delete-message
    defaults: { _controller: ZnaikaFrontendBundle:Message:deleteMessage }
    methods:  [POST]
    options:
        expose: true

login:
    path: /user-login
    defaults: { _controller: ZnaikaFrontendBundle:User:login }

login_check:
    path: /login-check

try_login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: login
        permanent: true
    options:
        expose: true

logout:
    path: /logout

vk_login:
    path: /vk-auth
    defaults: { _controller: ZnaikaFrontendBundle:User:vkLogin }

facebook_login:
    path: /facebook-auth
    defaults: { _controller: ZnaikaFrontendBundle:User:facebookLogin }

odnoklassniki_login:
    path: /odnoklassniki-auth
    defaults: { _controller: ZnaikaFrontendBundle:User:odnoklassnikiLogin }

search:
    pattern: /search
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideo }

search_video:
    pattern: /search/video/{searchString}
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideo }

search_video_ajax:
    pattern: /search/next-videos
    defaults: { _controller: ZnaikaFrontendBundle:Search:searchVideoAjax }
    methods:  [POST]
    options:
        expose: true

register_confirm:
    pattern: /register-confirm/{registerKey}
    defaults: { _controller: ZnaikaFrontendBundle:User:registerConfirm }

user_has_viewed_badges:
    pattern: /user-has-viewed-badges
    defaults: { _controller: ZnaikaFrontendBundle:User:hasViewedBadges }
    methods:  [POST]
    options:
        expose: true

add_video_attachment_form:
    pattern: /video/{videoName}/add-video-attachment-form
    defaults: { _controller: ZnaikaFrontendBundle:Video:addVideoAttachmentForm }

download_video_attachment:
    pattern: /video-attachment/{attachmentId}
    defaults: { _controller: ZnaikaFrontendBundle:Video:downloadVideoAttachment }
    requirements:
        attachmentId:  \d+

post_video_to_social_network:
    pattern: /post-video/{videoName}
    defaults: { _controller: ZnaikaFrontendBundle:Video:postVideoToSocialNetwork }
    methods:  [POST]
    options:
        expose: true

about:
    pattern: /about
    defaults: { _controller: ZnaikaFrontendBundle:Default:about }

contacts:
    pattern: /contacts
    defaults: { _controller: ZnaikaFrontendBundle:Default:contacts }

rules:
    pattern: /rules
    defaults: { _controller: ZnaikaFrontendBundle:Default:rules }

agreement:
    pattern: /agreement
    defaults: { _controller: ZnaikaFrontendBundle:Default:agreement }

support:
    pattern: /support
    defaults: { _controller: ZnaikaFrontendBundle:Support:addSupportForm }
