parameters:
    znaika.menu.class: Knp\Menu\MenuItem

services:
    message_send_listener:
        class: Znaika\FrontendBundle\EventListener\MessageSendSubscriber
        arguments: [@fos_message.message_manager]
        tags:
            - { name: kernel.event_subscriber }

    znaika.new_thread_form.type:
        class:     Znaika\FrontendBundle\Form\Communication\NewThreadMessageFormType

    znaika.messages_provider:
        class:     Znaika\FrontendBundle\Provider\MessagesProvider
        arguments:
            - @znaika.thread_repository
            - @znaika.message_repository
            - @fos_message.thread_reader
            - @fos_message.authorizer
            - @fos_message.participant_provider

    znaika.video_attachment_uploader:
        class:     Znaika\FrontendBundle\Helper\Uploader\VideoAttachmentUploader
        arguments: ['@service_container']

    znaika.quiz_uploader:
        class:     Znaika\FrontendBundle\Helper\Uploader\QuizUploader
        arguments: ['@service_container']

    znaika.synopsis_uploader:
        class:     Znaika\FrontendBundle\Helper\Uploader\SynopsisUploader
        arguments: ['@service_container']

    znaika.video_info_updater:
        class:     Znaika\FrontendBundle\Helper\Content\VideoInfoUpdater
        arguments:
            - @znaika.video_repository
            - @znaika.php_vimeo
            - @service_container

    znaika.php_vimeo:
        class:     Znaika\FrontendBundle\Helper\Vimeo
        arguments:
            - %vimeo_client_id%
            - %vimeo_client_secret%
            - %vimeo_access_token%
            - %vimeo_access_token_secret%

#repository
    znaika.video_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.video_comment_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoCommentRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.synopsis_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\SynopsisRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.subject_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\SubjectRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.chapter_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\ChapterRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.message_repository:
        class:        Znaika\FrontendBundle\Repository\Communication\MessageRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.thread_repository:
        class:        Znaika\FrontendBundle\Repository\Communication\ThreadRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.video_attachment_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Attachment\VideoAttachmentRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.quiz_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Attachment\QuizRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.quiz_attempt_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Stat\QuizAttemptRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.support_repository:
        class:        Znaika\FrontendBundle\Repository\Communication\Support\SupportRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika.region_repository:
        class:        Znaika\ProfileBundle\Repository\RegionRepository
        arguments:    ["@doctrine.orm.entity_manager"]

#menu
    znaika.menu_builder:
        class: Znaika\FrontendBundle\Menu\MenuBuilder
        arguments:
            - @knp_menu.factory
            - @security.context

    znaika.menu.main:
        class: "%znaika.menu.class%"
        factory_service: znaika.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    znaika.menu.sidebar_profile_menu:
        class: "%znaika.menu.class%"
        factory_service: znaika.menu_builder
        factory_method: createSidebarProfileMenu
        arguments:
            - @request
            - @znaika.user_repository
            - @znaika.video_comment_repository
            - @znaika.message_repository
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_profile_menu }

    znaika.menu.sidebar_grade_menu:
        class: "%znaika.menu.class%"
        factory_service: znaika.menu_builder
        factory_method: createSidebarGradeMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_grade_menu }

    znaika.menu.sidebar_subject_menu:
        class: "%znaika.menu.class%"
        factory_service: znaika.menu_builder
        factory_method: createSidebarSubjectMenu
        arguments: ["@request", "@znaika.subject_repository"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_subject_menu }

#form
    znaika.recipient_type:
        class:        Znaika\FrontendBundle\Form\Communication\RecipientType
        arguments:    ["@znaika.user_to_id_transformer"]
        tags:
            - { name: form.type, alias: recipient_input }

#twig
    znaika.video_comment_extension:
        class: Znaika\FrontendBundle\Twig\Video\CommentExtension
        arguments:
            - @twig
            - @security.context
            - @znaika.video_comment_repository
            - @form.factory
        tags:
            - { name: twig.extension }

    znaika.quiz_extension:
        class: Znaika\FrontendBundle\Twig\Video\QuizExtension
        arguments:
            - @twig
            - @znaika.quiz_uploader
        tags:
            - { name: twig.extension }

    znaika.thumbnail_extension:
        class: Znaika\FrontendBundle\Twig\Video\ThumbnailExtension
        tags:
            - { name: twig.extension }

    znaika.synopsis_extension:
        class: Znaika\FrontendBundle\Twig\Video\SynopsisExtension
        arguments:
            - @twig
            - @znaika.synopsis_uploader
        tags:
            - { name: twig.extension }

    znaika.date_extension:
        class: Znaika\FrontendBundle\Twig\DateExtension
        arguments:
            - @service_container
            - @translator
        tags:
            - { name: twig.extension }

    znaika.index_page_extension:
        class: Znaika\FrontendBundle\Twig\IndexPageExtension
        arguments:
            - @twig
            - @znaika.video_repository
            - @znaika.user_operation_repository
            - @znaika.user_repository
        tags:
            - { name: twig.extension }

    znaika.search_extension:
        class: Znaika\FrontendBundle\Twig\SearchExtension
        arguments:
            - @twig
            - @service_container
        tags:
            - { name: twig.extension }

    znaika.menu_helper_extension:
        class: Znaika\FrontendBundle\Twig\MenuHelperExtension
        arguments:
            - @znaika.subject_repository
        tags:
            - { name: twig.extension }

    znaika.message_extension:
        class: Znaika\FrontendBundle\Twig\MessageExtension
        arguments:
            - @znaika.message_repository
        tags:
            - { name: twig.extension }

#event listeners
    znaika.before_controller_listener:
        class: Znaika\FrontendBundle\EventListener\BeforeControllerListener
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

#monolog
    email_formatter:
        class: Monolog\Formatter\LineFormatter

    web_processor:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor, handler: mail }

    introspection_processor:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }

    uid_processor:
        class: Monolog\Processor\UidProcessor
        tags:
            - { name: monolog.processor }

    mpu_processor:
        class: Monolog\Processor\MemoryPeakUsageProcessor
        tags:
            - { name: monolog.processor, handler: mail }

#search
    znaika.video_search:
        class: Znaika\FrontendBundle\Helper\Search\VideoSearch
        arguments:
            - @znaika.video_repository
