parameters:
parameters:
    znaika_frontend.menu.class: Knp\Menu\MenuItem

services:
    znaika_frontend.new_thread_form.type:
        class:     Znaika\FrontendBundle\Form\Communication\NewThreadMessageFormType

    znaika_frontend.mail_helper:
        class:     Znaika\FrontendBundle\Helper\Mail\MailHelper
        arguments: ['@mailer']

    znaika_frontend.user_mailer:
        class:     Znaika\FrontendBundle\Helper\Mail\UserMailer
        arguments:
            - @znaika_frontend.mail_helper
            - @twig

    znaika_frontend.register_key_encoder:
        class:     Znaika\FrontendBundle\Helper\Encode\RegisterKeyEncoder

    znaika_frontend.user_authenticator:
        class:     Znaika\FrontendBundle\Helper\Security\UserAuthenticator
        arguments: ['@service_container']

    znaika_frontend.messages_provider:
        class:     Znaika\FrontendBundle\Provider\MessagesProvider
        arguments:
            - @znaika_frontend.thread_repository
            - @znaika_frontend.message_repository
            - @fos_message.thread_reader
            - @fos_message.authorizer
            - @fos_message.participant_provider

    znaika_frontend.user_operation_listener:
        class:     Znaika\FrontendBundle\Helper\UserOperation\UserOperationListener
        arguments:
            - @znaika_frontend.user_operation_repository
            - @znaika_frontend.user_badge_repository

    znaika_frontend.video_attachment_uploader:
        class:     Znaika\FrontendBundle\Helper\Uploader\VideoAttachmentUploader
        arguments: ['@service_container']

#repository
    znaika_frontend.video_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.video_comment_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoCommentRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.synopsis_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\SynopsisRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.subject_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\SubjectRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.chapter_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\ChapterRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\UserRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_registration_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\UserRegistrationRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.quiz_question_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\QuizQuestionRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.quiz_answer_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\QuizAnswerRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_attempt_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\Attempt\UserAttemptRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_question_answer_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\Attempt\UserQuestionAnswerRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.message_repository:
        class:        Znaika\FrontendBundle\Repository\Communication\MessageRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.thread_repository:
        class:        Znaika\FrontendBundle\Repository\Communication\ThreadRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_operation_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\Action\UserOperationRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.user_badge_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\Badge\UserBadgeRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    znaika_frontend.video_attachment_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Attachment\VideoAttachmentRepository
        arguments:    ["@doctrine.orm.entity_manager"]

#menu
    znaika_frontend.menu_builder:
        class: Znaika\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    znaika_frontend.menu.main:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    znaika_frontend.menu.sidebar_grade_menu:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarGradeMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_grade_menu }

    znaika_frontend.menu.sidebar_subject_menu:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarSubjectMenu
        arguments: ["@request", "@znaika_frontend.subject_repository"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_subject_menu }

#form
    znaika_frontend.recipient_type:
        class:        Znaika\FrontendBundle\Form\Communication\RecipientType
        arguments:    ["@znaika_frontend.user_to_id_transformer"]
        tags:
            - { name: form.type, alias: recipient_input }

    znaika_frontend.user_to_id_transformer:
        class:     Znaika\FrontendBundle\Form\DataTransformer\UserToIdTransformer
        arguments: ['@znaika_frontend.user_repository']

#twig
    znaika_frontend.badge_extension:
        class: Znaika\FrontendBundle\Twig\BadgeExtension
        arguments:
            - @twig
            - @znaika_frontend.user_badge_repository
        tags:
            - { name: twig.extension }

    znaika_frontend.index_page_extension:
        class: Znaika\FrontendBundle\Twig\IndexPageExtension
        arguments:
            - @twig
            - @znaika_frontend.video_repository
            - @znaika_frontend.user_operation_repository
            - @znaika_frontend.user_repository
            - @znaika_frontend.user_badge_repository
        tags:
            - { name: twig.extension }

    znaika_frontend.security_extension:
        class: Znaika\FrontendBundle\Twig\SecurityExtension
        arguments:
            - @security.context
        tags:
            - { name: twig.extension }