parameters:

services:
    znaika_frontend.menu_builder:
        class: Znaika\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    znaika_frontend.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: znaika_frontend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    znaika_frontend.menu.sidebar_grade_menu:
        class: Knp\Menu\MenuItem
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarGradeMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_grade_menu }

    znaika_frontend.menu.sidebar_subject_menu:
        class: Knp\Menu\MenuItem
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarSubjectMenu
        arguments: ["@request", "@doctrine.orm.entity_manager"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_subject_menu }