parameters:
    znaika_frontend.menu.class: Knp\Menu\MenuItem

services:
    mail_helper:
        class:     Znaika\FrontendBundle\Helper\Mail\MailHelper
        arguments: ['@mailer']
    user_mailer:
        class:     Znaika\FrontendBundle\Helper\Mail\UserMailer
        arguments:
            - @mail_helper
            - @twig
    register_key_encoder:
        class:     Znaika\FrontendBundle\Helper\Encode\RegisterKeyEncoder
    user_authenticator:
        class:     Znaika\FrontendBundle\Helper\Security\UserAuthenticator
        arguments: ['@service_container']
#repository
    video_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    video_comment_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoCommentRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    video_view_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\VideoViewRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    synopsis_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\SynopsisRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    subject_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\SubjectRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    chapter_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Category\ChapterRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    user_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\UserRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    user_registration_repository:
        class:        Znaika\FrontendBundle\Repository\Profile\UserRegistrationRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    quiz_question_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\QuizQuestionRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    quiz_answer_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\QuizAnswerRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    user_attempt_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\Attempt\UserAttemptRepository
        arguments:    ["@doctrine.orm.entity_manager"]

    user_question_answer_repository:
        class:        Znaika\FrontendBundle\Repository\Lesson\Content\Quiz\Attempt\UserQuestionAnswerRepository
        arguments:    ["@doctrine.orm.entity_manager"]

#menu
    znaika_frontend.menu_builder:
        class: Znaika\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    znaika_frontend.menu.main:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    znaika_frontend.menu.sidebar_grade_menu:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarGradeMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_grade_menu }

    znaika_frontend.menu.sidebar_subject_menu:
        class: "%znaika_frontend.menu.class%"
        factory_service: znaika_frontend.menu_builder
        factory_method: createSidebarSubjectMenu
        arguments: ["@request", "@subject_repository"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar_subject_menu }

