Znaika\FrontendBundle\Entity\Lesson\Content\Video:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [urlName]
            message: 'not_unique'
    properties:
        name:
            - NotBlank: { message: "not_blank" }
        url:
            - NotBlank: { message: "not_blank" }
        author:
            - NotBlank: { message: "not_blank" }

Znaika\FrontendBundle\Entity\Profile\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'not_unique_user_email'
    properties:
        email:
            - NotBlank: { message: "not_blank" }
            - Email:
                  checkMX: true
        password:
            - NotBlank: { message: "not_blank" }

Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\VideoAttachment:
    properties:
        file:
            - File:
                maxSize: 100M
                mimeTypes: [application/pdf, application/x-pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/msword]
                mimeTypesMessage: "invalid_attachment_file_format"

Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\Quiz:
    properties:
        file:
            - File:
                maxSize: 100M
                mimeTypes: [application/zip, application/x-zip, application/octet-stream, application/x-zip-compressed]
                mimeTypesMessage: "invalid_quiz_file_format"

Znaika\FrontendBundle\Entity\Profile\PasswordRecovery:
    properties:
        user:
            - NotNull: { message: "not_null" }
