Znaika\FrontendBundle\Entity\Lesson\Content\Video:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [urlName]
            message: 'not_unique'
        - Callback:
            methods:   [isChapterValid]
    properties:
        name:
            - NotBlank: { message: "not_blank" }
        grade:
            - NotBlank: { message: "not_blank" }
            - Znaika\FrontendBundle\Validator\Constraints\ClassNumber: ~
        urlName:
            - NotBlank: { message: "not_blank" }
        url:
            - NotBlank: { message: "not_blank" }

Znaika\FrontendBundle\Entity\Profile\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'not_unique'
    properties:
        email:
            - NotBlank: { message: "not_blank" }
            - Email:
                  checkMX: true
        password:
            - NotBlank: { message: "not_blank" }

Znaika\FrontendBundle\Entity\Lesson\Content\Attachment\VideoAttachment:
    properties:
        file:
            - File:
                maxSize: 100M
                mimeTypes: [application/pdf, application/x-pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/msword]
                mimeTypesMessage: "invalid_file_format"
